version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  nuget_package_id: $(APPVEYOR_PROJECT_NAME)
before_build:
- cmd: appveyor-retry nuget restore Source\%APPVEYOR_PROJECT_NAME%.sln
build:
  project: .\Source\$(APPVEYOR_PROJECT_NAME).sln
  verbosity: normal
after_build:
- cmd: .\Build\NuGet\Package.cmd
- appveyor PushArtifact %NUGET_PACKAGE_ID%.%APPVEYOR_BUILD_VERSION%.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: /0Z5Cw06AdhoTRWdDCY6lEf6mL6m2WzkA1KgiJnjwFfpHVgfdDMdqVHQPpnI1K6O
  skip_symbols: false
  artifact: /.*\.nupkg/